/**
 *  BodyPart.java
 *  Authored by Cody Fagley
 *  May 3, 2017
 */

/*
 *  List of human bodyparts
 */
package actor.human;

public enum Bodypart
{
    HEAD, TORSO, LEFT_ARM, LEFT_LEG, LEFT_HAND, LEFT_FOOT, RIGHT_ARM,
    RIGHT_LEG, RIGHT_HAND, RIGHT_FOOT, LEFT_THUMB_FINGER, LEFT_INDEX_FINGER,
    LEFT_MIDDLE_FINGER, LEFT_RING_FINGER, LEFT_PINKY_FINGER, 
    RIGHT_INDEX_FINGER, RIGHT_THUMB_FINGER, RIGHT_MIDDLE_FINGER, 
    RIGHT_RING_FINGER, RIGHT_PINKY_FINGER, LEFT_THUMB_TOE, LEFT_INDEX_TOE,
    LEFT_MIDDLE_TOE, LEFT_RING_TOE, LEFT_PINKY_TOE, RIGHT_THUMB_TOE,
    RIGHT_INDEX_TOE, RIGHT_MIDDLE_TOE, RIGHT_RING_TOE, RIGHT_PINKY_TOE, NONE
}
