/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.ui;

import com.sun.javafx.tk.Toolkit;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author cody
 */
public class App extends javax.swing.JFrame {

  /**
   * Creates new form App
   */
  public App() {
    initComponents();
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backgroundLabel = new javax.swing.JLabel();
        MainMenu = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        singleButton = new javax.swing.JButton();
        multiButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        grid00 = new javax.swing.JPanel();
        grid11 = new javax.swing.JPanel();
        grid22 = new javax.swing.JPanel();
        grid33 = new javax.swing.JPanel();
        grid44 = new javax.swing.JPanel();
        grid55 = new javax.swing.JPanel();
        grid66 = new javax.swing.JPanel();
        grid77 = new javax.swing.JPanel();
        grid88 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universe");
        setAlwaysOnTop(true);
        setBounds(this.getGraphicsConfiguration().getBounds());
        setUndecorated(true);
        setPreferredSize(this.getGraphicsConfiguration().getBounds().getSize());
        setSize(new java.awt.Dimension(0, 0));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mmBackground.jpg"))); // NOI18N

        MainMenu.setOpaque(false);
        MainMenu.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Serto Kharput", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Exploration: Universe");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(titleLabel, gridBagConstraints);

        singleButton.setFont(new java.awt.Font("Serto Jerusalem", 1, 18)); // NOI18N
        singleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/playButtonInactive.png"))); // NOI18N
        singleButton.setBorder(null);
        singleButton.setContentAreaFilled(false);
        singleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                singleButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                singleButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                singleButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Hover(evt);
            }
        });
        singleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(singleButton, gridBagConstraints);

        multiButton.setFont(new java.awt.Font("Serto Jerusalem", 1, 18)); // NOI18N
        multiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/multiButtonInactive.png"))); // NOI18N
        multiButton.setBorder(null);
        multiButton.setContentAreaFilled(false);
        multiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                multiButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                multiButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverEnter(evt);
            }
        });
        multiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(multiButton, gridBagConstraints);

        optionsButton.setFont(new java.awt.Font("Serto Jerusalem", 1, 18)); // NOI18N
        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/optionsButtonInactive.png"))); // NOI18N
        optionsButton.setBorder(null);
        optionsButton.setBorderPainted(false);
        optionsButton.setContentAreaFilled(false);
        optionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                optionsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                optionsButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionsButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionsButtonMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(optionsButton, gridBagConstraints);

        exitButton.setFont(new java.awt.Font("Serto Jerusalem", 1, 18)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitButtonInactive.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitButtonMouseReleased(evt);
                closeProgram(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(exitButton, gridBagConstraints);

        grid00.setOpaque(false);

        javax.swing.GroupLayout grid00Layout = new javax.swing.GroupLayout(grid00);
        grid00.setLayout(grid00Layout);
        grid00Layout.setHorizontalGroup(
            grid00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid00Layout.setVerticalGroup(
            grid00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid00, gridBagConstraints);

        grid11.setOpaque(false);

        javax.swing.GroupLayout grid11Layout = new javax.swing.GroupLayout(grid11);
        grid11.setLayout(grid11Layout);
        grid11Layout.setHorizontalGroup(
            grid11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        grid11Layout.setVerticalGroup(
            grid11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid11, gridBagConstraints);

        grid22.setOpaque(false);

        javax.swing.GroupLayout grid22Layout = new javax.swing.GroupLayout(grid22);
        grid22.setLayout(grid22Layout);
        grid22Layout.setHorizontalGroup(
            grid22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid22Layout.setVerticalGroup(
            grid22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid22, gridBagConstraints);

        grid33.setOpaque(false);

        javax.swing.GroupLayout grid33Layout = new javax.swing.GroupLayout(grid33);
        grid33.setLayout(grid33Layout);
        grid33Layout.setHorizontalGroup(
            grid33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid33Layout.setVerticalGroup(
            grid33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid33, gridBagConstraints);

        grid44.setOpaque(false);

        javax.swing.GroupLayout grid44Layout = new javax.swing.GroupLayout(grid44);
        grid44.setLayout(grid44Layout);
        grid44Layout.setHorizontalGroup(
            grid44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid44Layout.setVerticalGroup(
            grid44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid44, gridBagConstraints);

        javax.swing.GroupLayout grid55Layout = new javax.swing.GroupLayout(grid55);
        grid55.setLayout(grid55Layout);
        grid55Layout.setHorizontalGroup(
            grid55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid55Layout.setVerticalGroup(
            grid55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid55, gridBagConstraints);

        grid66.setOpaque(false);

        javax.swing.GroupLayout grid66Layout = new javax.swing.GroupLayout(grid66);
        grid66.setLayout(grid66Layout);
        grid66Layout.setHorizontalGroup(
            grid66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid66Layout.setVerticalGroup(
            grid66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid66, gridBagConstraints);

        grid77.setOpaque(false);

        javax.swing.GroupLayout grid77Layout = new javax.swing.GroupLayout(grid77);
        grid77.setLayout(grid77Layout);
        grid77Layout.setHorizontalGroup(
            grid77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid77Layout.setVerticalGroup(
            grid77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid77, gridBagConstraints);

        grid88.setOpaque(false);

        javax.swing.GroupLayout grid88Layout = new javax.swing.GroupLayout(grid88);
        grid88.setLayout(grid88Layout);
        grid88Layout.setHorizontalGroup(
            grid88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grid88Layout.setVerticalGroup(
            grid88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMenu.add(grid88, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1975, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singleButtonActionPerformed

    private void multiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiButtonActionPerformed

    private void Hover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hover
        singleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/playButtonHover.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_Hover

    private void singleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singleButtonMouseExited
        singleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/playButtonInactive.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_singleButtonMouseExited

    private void singleButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singleButtonMousePressed
        singleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/playButtonPressed.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_singleButtonMousePressed

    private void singleButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singleButtonMouseReleased
        singleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/playButtonInactive.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_singleButtonMouseReleased

    private void HoverEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverEnter
        multiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/multiButtonHover.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_HoverEnter

    private void multiButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiButtonMouseExited
        multiButton.setIcon(new ImageIcon(getClass().getResource("/assets/multiButtonInactive.png")));
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_multiButtonMouseExited

    private void multiButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiButtonMousePressed
        multiButton.setIcon(new ImageIcon(getClass().getResource("/assets/multiButtonPressed.png")));
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_multiButtonMousePressed

    private void multiButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiButtonMouseReleased
        multiButton.setIcon(new ImageIcon(getClass().getResource("/assets/multiButtonInactive.png")));
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_multiButtonMouseReleased

    private void optionsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsButtonMouseEntered
        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/optionsButtonHover.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_optionsButtonMouseEntered

    private void optionsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsButtonMouseExited
        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/optionsButtonInactive.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_optionsButtonMouseExited

    private void optionsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsButtonMousePressed
        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/optionsButtonPressed.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_optionsButtonMousePressed

    private void optionsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsButtonMouseReleased
        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/optionsButtonInactive.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_optionsButtonMouseReleased

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitButtonHover.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitButtonInactive.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitButtonPressed.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_exitButtonMousePressed

    private void exitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitButtonInactive.png"))); // NOI18N
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_exitButtonMouseReleased

    private void closeProgram(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeProgram
        System.exit(0);
    }//GEN-LAST:event_closeProgram

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMenu;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel grid00;
    private javax.swing.JPanel grid11;
    private javax.swing.JPanel grid22;
    private javax.swing.JPanel grid33;
    private javax.swing.JPanel grid44;
    private javax.swing.JPanel grid55;
    private javax.swing.JPanel grid66;
    private javax.swing.JPanel grid77;
    private javax.swing.JPanel grid88;
    private javax.swing.JButton multiButton;
    private javax.swing.JButton optionsButton;
    private javax.swing.JButton singleButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
